# Generated by Django 6.0.4 on 2026-05-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name="Date de l'événement")),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cond_filiere', models.CharField(blank=True, choices=[('GENIE_IND', 'Génie Industriel'), ('FINANCE', 'Finance'), ('RESEAUX', 'Réseaux Informatiques'), ('PREPA', 'Classe Préparatoire')], max_length=20, null=True, verbose_name='Filière requise (laisser vide = toutes)')),
                ('cond_annee_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année minimale requise')),
                ('cond_annee_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année maximale requise')),
                ('cond_age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge minimum requis')),
                ('cond_age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge maximum requis')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.evenement')),
            ],
        ),
    ]
