# Generated by Django 6.0.4 on 2026-05-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='events/covers/'),
        ),
        migrations.CreateModel(
            name='EvenementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='events/gallery/')),
                ('legende', models.CharField(blank=True, max_length=120)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='events.evenement')),
            ],
        ),
    ]
