# Generated by Django 6.0.4 on 2026-05-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ajout_filiere_annee_age_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='club',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Adhesion',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
