# Generated by Django 6.0.4 on 2026-05-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('cond_filiere', models.CharField(blank=True, choices=[('GENIE_IND', 'Génie Industriel'), ('FINANCE', 'Finance'), ('RESEAUX', 'Réseaux Informatiques'), ('PREPA', 'Classe Préparatoire')], max_length=20, null=True, verbose_name='Filière requise (laisser vide = toutes)')),
                ('cond_annee_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année minimale requise')),
                ('cond_annee_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année maximale requise')),
                ('cond_age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge minimum requis')),
                ('cond_age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Âge maximum requis')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_geres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='ATTENTE', max_length=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_adhesion', to='clubs.club')),
            ],
        ),
    ]
