# Generated by Django 6.0.4 on 2026-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='clubs/logos/'),
        ),
    ]
